<div class="page-header">
    <h1 style=" padding-top: 50px;">Collaborateur</h1>
    <p>Ceci est la page des différents collaborateurs.</p>
    <p>Les collaborateurs sont :</p>
            <ul>
                <li>des <b>chefs de projet</b> ;</li>
                <li>des développeurs <b>FrontEnd</b> et <b>BackEnd</b> ;</li>
                <li>des <b>administrateurs de base de données</b>.</li>
             </ul>
    <p>Ils disposent tous d'un Niveau de compétence.</p>
    <table class="table">
        <thead>
        <th>Prénom</th>
        <th>Nom</th>
        <th>Niveau de compétence</th>
         <th>Prime</th>
        </thead>
        <tbody>

        <?php foreach ($this->view->collabsForTable as $collaborateur) {?>
            <tr>
                <td><?php echo $collaborateur['prenom']?></td>
                <td><?php echo $collaborateur['nom']?></td>
                <td><?php echo $collaborateur['niveau_competence']?></td>
                <td><?php echo $collaborateur['prime']?></td>
            </tr>
        <?php } ?>

        </tbody>
    </table>
</div>

