<div class="page-header">
    <h1 style=" padding-top: 50px;">Client</h1>
    <p>Ceci est la page des Clients :</p>
    <table class="table">
        <thead>
            <th>Raison sociale</th>
            <th>RIDET</th>
            <th>SS2I</th>
        </thead>
        <tbody>
        <?php foreach ($this->view->clientForTable as $client) {?>
            <tr>
                <td><?php echo $client['raison_sociale']?></td>
                <td><?php echo $client['ridet']?></td>
                <td><?php echo $client['ss2i']?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

