<div class="page-header">
    <h1 class="container" style="text-align: center; padding-top: 50px;">Bonjour et bienvenue dans le jeu WebAppSaler</h1>
    <p>Vous incarnez un développeur talentueux et créatif qui doit concevoir, construire et améliorer des projets uniques.</p>
    <p>Choisissez votre domaine de prédilection, relevez des défis passionnants, gagnez de l'expérience et débloquez de nouvelles opportunités.</p>
    <p>Exprimez votre créativité et repoussez les limites de la création numérique.</p>
    <p>Prêt à jouer ?</p>
    <hr>
    <!-- Bouton Lancer une partie ouvre un popup avec le choix du projet et la composition de l'équipe -->
    <h2 style="text-align: center;">Pour commencer, créer une partie</h2>
    <hr>
    <label for="client-select">Choisissez un client :</label>
    <div style="display: flex; align-items: center;">
        <select style="flex: 1;" id="client" name="client-select">
            <?php foreach ($this->view->clientsOptions as $client) {?>
                <option value="<?php echo $client['value']?>"><?php echo $client['label']?></option>
            <?php } ?>
        </select>
    </div>
    <br>
    <label for="projet-select">Choisissez un projet :</label>
    <div style="display: flex; align-items: center;">

        <select style="flex: 1;" id="projet-select" name="projet-select">
            <?php foreach ($this->view->projetsOptions as $projet) {?>
                <option value="<?php echo $projet['value']; ?>"><?php echo $projet['label']; ?></option>
            <?php } ?>
        </select>
    </div>
    <br>
    <label for="chefDeProjets-select">Ajouter un chef de projet :</label>
    <div style="display: flex; align-items: center;">
        <select style="flex: 1;" id="chefDeProjets" name="chefDeProjets" id="chefDeProjets-select">
            <?php foreach ($this->view->chefDeProjets as $chefDeProjet) {?>
                <option value="<?php echo $chefDeProjet['value']?>"><?php echo $chefDeProjet['label']?></option>
            <?php } ?>
        </select>
        <button type="button" style="margin-left: 20px;">+</button> <!-- Bouton d'ajout -->
    </div>
    <br>
    <label for="developpeur-select">Ajouter des développeurs :</label>
    <div style="display: flex; align-items: center;">
        <select style="flex: 1;" name="developpeur" id="developpeur-select">
            <?php foreach ($this->view->developpeurs as $developpeur) {?>
                <option value="<?php echo $developpeur['value']?>"><?php echo $developpeur['label']?></option>
            <?php } ?>
        </select>
        <button style="margin-left: 20px;" type="button">+</button> <!-- Bouton d'ajout -->
    </div>
    <br><br>
    <div id="addedMembers">
        <!-- Zone d'affichage des membres de l'équipe ajoutés -->
        <h3>Membres de l'équipe ajoutés</h3>
        <ul id="teamMembers" style="list-style-type: none; padding: 0;"></ul>
    </div>
    <button type="button"">Créer</button>
</div>
