<!DOCTYPE html>

<html>

<head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">

        <span class="navbar-toggler-icon"></span>

    </button>

    <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav">
            <li class="nav-item">

                <a class="nav-link" href="index">Accueil</a>

            </li>

            <li class="nav-item">

                <a class="nav-link" href="collaborateur">Collaborateurs</a>

            </li>
            <li class="nav-item">

                <a class="nav-link" href="chefDeProjet">Chefs de projet</a>

            </li>


            <li class="nav-item">

                <a class="nav-link" href="projet">Types de projets</a>

            </li>

            <li class="nav-item">

                <a class="nav-link" href="client">Clients</a>

            </li>




        </ul>

    </div>

</nav>


<!-- Le reste du contenu de votre page -->


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

</html>

